### ISSUE TITLE
Creating server

### ISSUE THREAD

**Issue by jammersonf** [protonemedia/eddy-server-management#1]
I entered the digitalocean credentials and created a server. But in the configuration step, it creates the server in the DO, but does not recognize that it was created and does not exit this step.

![image](https://github.com/protonemedia/eddy-server-management/assets/2231447/f5fc4e1f-0e3b-48f5-863c-bbd8b586818f)

Can you explain to me how this update works? horizon is already active

Remembering that it is a self-hosted version and the DO token has read and write p

**Comment by SamuelNitsche** [comment]
I had the same problem. Be sure to correctly configure the app url clear the cache.

**Comment by pandeydip** [comment]
I am also stuck with the same problem, Has anyone managed to run successfully hosting it on your own server? If yes, please provide the installation guide. It's stuck in the second step 'wait for the server to startup'.

Could you please guide @pascalbaljet

**Comment by pandeydip** [comment]
> Be sure to correctly configure the app url clear the cache



> You need to configure pusher into `.env` file , change the broadcast driver to the `pusher`. change queye driver to redis. Also need active mail smtp, otherwise server provisioned will be failed and deleted automatically. Then run `php artisan optimize:clear` Then start horizon `php artisan horizon`

@fftfaisal How you manage

> I entered the digitalocean credentials and created a server. But in the configuration step, it creates the server in the DO, but does not recognize that it was created and does not exit this step.
> 
> ![image](https://user-images.githubusercontent.com/2231447/241245791-f5fc4e1f-0e3b-48f5-863c-bbd8b586818f.png)
> 
> Can you explain to me how this update works? horizon is already active
> 
> Remembering that it is a self-hosted version and the DO token has read and write 

@jammersonf How you managed to solve this issue,

I configured the pusher, and also set up and stated horizon, only server creation works on DO and then it got stuck in the second step.

**Comment by pandeydip** [comment]
Thanks, finally managed to solve it by changing certain .env variables

**Comment by pascalbaljet** [comment]
I'll soon write a guide to set it up!

**Comment by pascalbaljet** [comment]
Here it is! 

https://github.com/protonemedia/eddy-server-management/blob/main/INSTALL.md

**Comment by netcarver** [comment]
@pascalbaljet Hello Pascal, thank you for the new document. I'm trying Eddy for the first time using your document and am a little confused as to why the first install script for a stand-alone server installs Protone Media's public SSH key into /root/.ssh/authorized_keys. Is this only used for initial provisioning and then gets removed at a later stage of the install process?

**Comment by RichieMcMullen** [comment]
php artisan horizon command just times out.

**Comment by omaralalwi** [comment]
> pandeydip

can you show me how yo solved

**Comment by hosamalzagh** [comment]
+1
