### ISSUE TITLE
Feature-Request: Add support for installing Security-Key resident puiblic SSH key parts.

### ISSUE THREAD

**Issue by netcarver** [protonemedia/eddy-server-management#10]
Attempting to add an sk-ecdsa SSH public key fails. 

I have a Yubikey with a key-resident SSH key. The public part is present in my /home/user/.ssh/ directory but attempting to add the public key fails with this message:

![image](https://github.com/protonemedia/eddy-server-management/assets/16049/93e50b46-2dd4-4499-baf0-a7fee8198cbc)

(I've redacted some of the public key string in the above - but the error was shown prior to redaction.)

Could this be due to lack of support for key-resident ssh keys in the phpseclib library?

**Comment by pascalbaljet** [comment]
That’s indeed the problem! I’ve found a workaround by using `ssh-keygen`. Will open a PR later today!
